create database customer_behaviour;

use customer_behaviour
go

create schema cb

select * from cb.CustomerTable;

exec sp_rename 'cb.CustomerTable','c_table';

select top 20 * from cb.c_table;

--Q1. What is the total revenue generated by male vs. female customers?

select
	gender as Gender,
	sum(purchase_amount) as [Total Revenue]
from cb.c_table
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

	select * from cb.c_table;

select
	*
from cb.c_table
where discount_applied = 'Yes' 
and
purchase_amount >= (select AVG(purchase_amount) from cb.c_table)
	
-- Q3. Which are the top 5 products with the highest average review rating?

select
	top 5 item_purchased as Product,
	round(avg(review_rating),2) as [Average Rating]
from cb.c_table
group by item_purchased 
order by AVG(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select
	shipping_type,
	avg(purchase_amount) as Average
from cb.c_table
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select
	subscription_status as [Subsription Status],
	count(customer_id) as [Total Customers],
	AVG(purchase_amount) as [Average Purchase Amount],
	sum(purchase_amount) as [Total Amount]
from cb.c_table
group by subscription_Status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
	top 5 item_purchased,
	(sum(case when discount_applied = 'Yes' then 1 else 0 end)*100.0 / count(*)) as Percentage
from cb.c_table
group by item_purchased
order by Percentage desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_Segment as
(select
	customer_id,
	previous_purchases,
	case
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
	end as Category
from cb.c_table)

select
	category,
	count(*) as [Total Customer]
from customer_Segment
group by category
order by count(*) desc

--Q8. What are the top 3 most purchased products within each category? 

select
	category,
	item_purchased,
	[Total Count]
from (
	select
		category,
		item_purchased,
		count(*) as [Total Count],
		row_number() over (partition by category order by count(*) desc) as [Rank]
	from cb.c_table
	group by category, item_purchased
	) as ranked
where [Rank]<=3
order by category, [Total Count] desc
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
	subscription_status,
	count(*)
from cb.c_table
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select
	*
from cb.c_table

select
	age_group,
	sum(purchase_amount) as [Total Revenue]
from cb.c_table
group by age_group
order by [Total Revenue] desc